name: NCTL Scan Dockerfile Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  # pull_request:
  #   branches:
  #     - "main"
  push:
    branches:
      - "main"

jobs:
  NCTL-Scan-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: nctl-scan-installer
        uses: nirmata/action-install-nctl-scan@v0.0.4

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check nctl version
        run: nctl version

      - name: NCTL Scan - Dockerfile
        run: nctl scan dockerfile --policies controls/dockerfile-best-practices --resources config-files/dockerfile/Dockerfile
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
